export const iconNames = [
	'alert',
	'arrow-down',
	'arrow-left',
	'arrow-right',
	'attachment',
	'audio-file',
	'bullet-points',
	'call-end',
	'call-ingoing',
	'call',
	'caret-down',
	'chat-bubble',
	'chat-widget',
	'close-circle',
	'csv-file',
	'doc-file',
	'double-chevron-down',
	'edit',
	'emoji',
	'envelope',
	'export',
	'filter-funnel',
	'generic-file',
	'home',
	'menu',
	'message',
	'missed-chat',
	'mute',
	'pdf-file',
	'plus',
	'popout',
	'search',
	'searches',
	'send',
	'share-screen',
	'text-file',
	'thumbs-down',
	'thumbs-up',
	'user',
	'video-call-off',
	'video-call-on',
	'video-file',
	'volume-down',
	'volume-up',
	'warning-triangle',
	'x',
] as const;

export type IIconName = typeof iconNames[number];

export const iconSizes = [
	'xsmall',
	'small',
	'medium',
	'large',
	'xlarge',
	'xxlarge',
] as const;

export type IIconSize = typeof iconSizes[number];
